# Generated by Django 3.2.5 on 2021-07-26 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210723_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='projects.project'),
        ),
    ]
